version: pcut-0.1-b{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      CMAKE_VS_ID: 12
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_VS_ID: 14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_VS_ID: 15

platform: x64

before_build:
  - mkdir "%APPVEYOR_BUILD_FOLDER%\build"
  - pushd "%APPVEYOR_BUILD_FOLDER%\build"
  - cmake -G "Visual Studio %CMAKE_VS_ID% Win64" -DCMAKE_BUILD_TYPE=Release ..

build_script:
  - pushd "%APPVEYOR_BUILD_FOLDER%\build"
  - cmake --build . --config Release

test_script:
  - pushd "%APPVEYOR_BUILD_FOLDER%\build"
  - ctest -C Release
